### ISSUE TITLE
Grant profile does not allow mixed types

### ISSUE THREAD

**Issue by shawnholt** [JMAConsulting/biz.jmaconsulting.grantapplications#110]
I'm exploring the Grant functionality for an exploratory discussion with a potential client.

First, I Now understand the true value of this extension, **not only does it create a page for Grants, but it also enables profiles to support Grant field types!**  Without it, you must assign grant fields to an individual or organization (which I may have to resort to...) This makes The extension indispensable for collecting grants online.

My problem is with mixing field Types on a profile form, I believe this has been addressed for some complex field mixing on profiles, but when I add a Grant field and individual or contact field I'm unable to create the Forum in WordPress (http://wiki.civicrm.org/confluence/display/CRM/Multiple-record+Custom+Data+Sets+in+Profiles)

**The error is: "Profile search, view and edit are not supported for Profiles which include fields for more than one record type."  I do not have view or search enabled.  just trying to create.**

I see this referenced here: https://issues.civicrm.org/jira/browse/CRM-4363

This means I can't ask for a first and last name, and birthday.

** A possible workaround for this is to support an arbitrary number of profiles **(I see just 2 supported) like with Event registration.

**Is this a limitation of the extension or am I doing something wrong?**

**Comment by shawnholt** [comment]
Note, the Grant Application Page does show the mixed profile: http://example.org/civicrm?page=CiviCRM&q=civicrm/grant/transact&reset=1&id=1

However, the wordpress Widget is only for the Profile, it is not for the page so it will not work.

**Comment by JoeMurray** [comment]
Sorry for slow reply. Edit and create are generally treated similarly for certain things like this message. 

The problem is not expected behaviour. You should be able to have core and custom fields for contact, individual, grant all on one profile. 

Can you provide CiviCRM, extension, and WordPress versions? Are you able to replicate on wp46. demo.civicrm.org?

**Comment by shawnholt** [comment]
Thx.  Will send tomorrow am.

**Comment by shawnholt** [comment]
I am using this on 4.6.4 + wordpress (latest).  Running as admin.
I enable Grants + Extension
Create a profile and include individual First, Last
Include Grant custom fields
Click preview and it works
Click Use (Create Mode)
Error: Sorry but we are not able to provide this at the moment.
The requested Profile (gid=18) is not configured to be used for 'Profile' edit and view forms in its Settings. Contact the site administrator if you need assistance.

Let me know what else i can try.

```
Jul 17 12:47:07  [info] $Fatal Error Details = Array
(
    [message] => The requested Profile (gid=18) is not configured to be used for 'Profile' edit and view forms in its Settings. Contact the site administrator if you need assistance.
    [code] =>
)

Jul 17 12:47:07  [info] $backTrace = #0 /home/xxxxx/public_html/wp-content/plugins/civicrm/civicrm/CRM/Core/Error.php(363): CRM_Core_Error::backtrace("backTrace", TRUE)
#1 /home/xxxxx/public_html/wp-content/plugins/civicrm/civicrm/CRM/Profile/Form/Edit.php(136): CRM_Core_Error::fatal("The requested Profile (gid=18) is not configured to be used for 'Profile' edi...")
#2 /home/xxxxx/public_html/wp-content/plugins/civicrm/civicrm/CRM/Core/Form.php(455): CRM_Profile_Form_Edit->preProcess()
#3 /home/xxxxx/public_html/wp-content/plugins/civicrm/civicrm/CRM/Core/QuickForm/Action/Display.php(94): CRM_Core_Form->buildForm()
#4 /home/xxxxx/public_html/wp-content/plugins/civicrm/civicrm/packages/HTML/QuickForm/Controller.php(203): CRM_Core_QuickForm_Action_Display->perform(Object(CRM_Profile_Form_Edit), "display")
#5 /home/xxxxx/public_html/wp-content/plugins/civicrm/civicrm/packages/HTML/QuickForm/Page.php(103): HTML_QuickForm_Controller->handle(Object(CRM_Profile_Form_Edit), "display")
#6 /home/xxxxx/public_html/wp-content/plugins/files/civicrm/extensions/biz.jmaconsulting.grantapplications/CRM/Core/Controller.php(359): HTML_QuickForm_Page->handle("display")
#7 /home/xxxxx/public_html/wp-content/plugins/civicrm/civicrm/CRM/Utils/Wrapper.php(115): CRM_Core_Controller->run()
#8 /home/xxxxx/public_html/wp-content/plugins/civicrm/civicrm/CRM/Profile/Page/Router.php(118): CRM_Utils_Wrapper->run("CRM_Profile_Form_Edit", "Create Profile", (Array:2))
#9 /home/xxxxx/public_html/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(312): CRM_Profile_Page_Router->run((Array:3), NULL)
#10 /home/xxxxx/public_html/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(86): CRM_Core_Invoke::runItem((Array:14))
#11 /home/xxxxx/public_html/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(54): CRM_Core_Invoke::_invoke((Array:3))
#12 /home/xxxxx/public_html/wp-content/plugins/civicrm/civicrm.php(1189): CRM_Core_Invoke::invoke((Array:3))
#13 [internal function](): CiviCRM_For_WordPress->invoke("")
#14 /home/xxxxx/public_html/wp-includes/plugin.php(496): call_user_func_array((Array:2), (Array:1))
#15 /home/xxxxx/public_html/wp-admin/admin.php(226): do_action("toplevel_page_CiviCRM")
#16 {main}
```

**Comment by shawnholt** [comment]
fyi, not able to repoen this or use extensions on the demo stack :(

**Comment by JoeMurray** [comment]
Thanks, @shawnholt. We'll get back to you if we need more info.

**Comment by pradpnayak** [comment]
Hi @shawnholt 

The issue is more of configuration rather extension. This error usually occurs when the profile you trying to use in create mode is not configured as 'Standalone Form or Directory'. 

Could you please check if 'Standalone Form or Directory' is checked on profile settings page?

Another note, Profile having more then one type are not allowed to be used as create/edit mode. So in your case you have includes fields of type Individual and Grants, which is not allowed by CiviCRM as it is difficult to interpret the data to be stored in the database.

HTH
Pradeep

**Comment by shawnholt** [comment]
Hi @pradpnayak 
thanks.  Again, the goal is to create a grant profile with mixed types.  This means, for example, 
   * First, Last name (Individual)
   * Address (Contact)
   * Grant Status (Grant)

(with custom fields for those entities)

**From what I can tell this is what @JoeMurray says "should" work.**
I have confirmed 3 times that this is not possible (2x WP, once in Drupal.)
I have standalone form checked (different error otherwise)

I know that mixed field types on profiles used to be a problem but was fixed a while ago (not sure how) but I think it is important for the use case (and consistency with how profiles work with other objects.)

BTW - You might add to the description somewhere that this module allows Grant profiles (in addition to the application page) as it allows even more capability than one might expect.

**Comment by pradpnayak** [comment]
Hi @shawnholt 

Here is the explanation in more detail :-

1. Grant application extension allows to create profiles that includes Grant core and custom fields and even contact and individual/household/organization core and custom fields. This profiles can be used in Grant application form to store the details that may be required during submission of Grant from online.

2. CiviCRM also allows to use profile as Standalone forms in create or edit mode, eg New Individual Profile submission would create/update the New Individual in the database.

In case 1 we can have mix type profile configured for grant application form i.e Individual/Household./Organization Profile with Contact field and Only Grant fields other fields are not allowed in the profile form.

In case 2 Profile create/edit mode are only allowed for Profile type having Individual/Household/Organization and Contact fields. Other Profile type's like Contribution, Participant, Membership, Grant etc fields cannot be used in Profile create/edit mode.

I think you are trying to use the profile in create mode i.e case 2. You should have got the error as 'Profile search, view and edit are not supported for Profiles which include fields for more than one record type.'.

**Comment by shawnholt** [comment]
Ah - wonderful explanation Pradeep. I'm sorry to be so persistent.  now I understand some subtitles here. Profile form cannot follow a relationship (ie. grant->contact) which is an unfortunate limitation.

There is something a bit off that threw me off.
Usually when you have a mixed / unsupported type, the create option goes away: http://screencast.com/t/xL3oDRHf5
but it didn't here for grants: http://screencast.com/t/u56Qgcoy .

Drupal the admin menu does work to remove for Grant:  http://screencast.com/t/sVd0R3W8 to http://screencast.com/t/1VCob5bWUw 

However in Wordpress it is not removed in the widget: http://screencast.com/t/UCmhXac7Au 

Perhaps the most confusing part (not related to grants of course) is the message you get when using profile create: "Profile search, view and edit are not supported for Profiles which include fields for more than one record type."

Side note: one reason I wanted to use profiles is that the grant application in question is quite long. I really wanted to break into multiple profiles.  Should I make a feature request to support more than 2 profiles (unlikely to get funded as making one long profile is a work-around.)

**Comment by JoeMurray** [comment]
1. I've created an issue for the WordPress problem wrt profile create not being disabled.

2. Could you suggest a better wording for the message?

3. Others have expressed an interest in having multiple tabs for a long application. Is that more what you are thinking about, rather than just two profiles on same form? The cost of that is significant - we were considering waiting for core team to develop a general solution for tabbed forms in core, or perhaps an extension to support integrating WordPress forms and CiviCRM. One effort has been started, but it doesn't seem to be going in a direction that makes sense.

**Comment by shawnholt** [comment]
For 1.+2. It needs to add "Create" to the message.
Message: "Cannot create, edit, search or view profiles with mixed record types."  

Help: "Mixing record types (other than contact and individual) is only supported in a component or extension that can manage the relationships between the types.  Profiles Standalone, Create, Edit Search or View Mode cannot automatically create the relationship, but when used with components that support profiles such as Event or Contribution Pages they can support relevant mixed record types.  For example, Event registration, could include participant and contacts fields because it includes the logic to associate them."

For 3. I was thinking that template/css/javascript might be a band-aid but getting multiple profiles would help that.  The "right" way would perhaps allow multiple profiles and have an option to display inline, as next page or tab.  A start would be to support multiple forms. Events now support an arbitrary number of profiles (although not elegantly) I wonder if something could be "borrowed" from there.

Sorry for the rant (feel free to delete) but 
I'm about to throw in the towel on wordpress (if the client agrees) as drupal webforms and entities give a humble system builder like me much more control.  IMO civicrm should get out of the forms business entirely (other than a basic/starter form) and let the CMS do that.  Gravity Forms, Webform, Entity Form can cover many more use cases.  [CivicrmEntity](https://www.drupal.org/project/civicrm_entity) has done that well for Drupal, and ideally something like wordpress [Pods](http://pods.io/) or exposing Civicrm entities as custom post types would do it for WP.

**Comment by JoeMurray** [comment]
Thanks for this, including the rant. The issue from the core team's perspective and a few of us 'core' extension developers is the effort to develop and maintain the software to enable a good forms experience in the three CMSes. I will pass on your message about Pods to relevant people like Tim, Coleman and Kevin Christiano. Do you know of something similar to CiviCRM Entity and Pods for Joomla!?

**Comment by shawnholt** [comment]
Sorry, I don't speak Joomla.  
I tried to get the pods guys excited about this but it didn't get very far.  https://wordpress.org/support/topic/work-with-api-and-remote-entities?replies=4 .  There are a couple of toolsets for custom wordpress post types that could potentially fit which I can share if you want to dig deeper down this path.
