### ISSUE TITLE
WordPress enables use of Mixed Profile for create

### ISSUE THREAD

**Issue by JoeMurray** [JMAConsulting/biz.jmaconsulting.grantapplications#115]
From another issue about profiles containing both grant and contact fields from @shawnholt:

There is something a bit off that threw me off.
Usually when you have a mixed / unsupported type, the create option goes away: http://screencast.com/t/xL3oDRHf5
but it didn't here for grants: http://screencast.com/t/u56Qgcoy .

Drupal the admin menu does work to remove for Grant: http://screencast.com/t/sVd0R3W8 to http://screencast.com/t/1VCob5bWUw

However in Wordpress it is not removed in the widget: http://screencast.com/t/UCmhXac7Au

**Comment by JoeMurray** [comment]
Please backport to 4.6 branch.

**Comment by pradpnayak** [comment]
Fixed at 
https://github.com/civicrm/civicrm-core/pull/7957
https://github.com/civicrm/civicrm-core/pull/7958
