### ISSUE TITLE
Change the error message and add help to field

### ISSUE THREAD

**Issue by JoeMurray** [JMAConsulting/biz.jmaconsulting.grantapplications#116]
1. Could you change the error message so that it includes 'Create':

Error Message: "Cannot create, edit, search or view profiles with mixed record types."

2. Could you find a good place to add the following help:

Help: "Mixing record types (other than contact, contact type (eg Individual), and contact custom subtype fields) is only supported in a component or extension that can manage the relationships between the types. Profiles Standalone, Create, Edit Search or View Mode cannot automatically create or find the related records. When profiles are used in components like Event or Contribution Pages they can support relevant mixed record types. For example, Event registration, could include participant and contacts fields because it includes the logic to associate them."

**Comment by Edzelopez** [comment]
Joe, should I submit a PR to core for this?
What we can do is;

1. Don't display the create profile button when there is a mixed profile which isn't compatible.
2. Include the help message instead of the button as a help icon.
3. Include the error message if the user tries to hit the URL directly.

**Comment by JoeMurray** [comment]
Can you send me a screen shot, marked up with how you would implement 2?

**Comment by Edzelopez** [comment]
![szoter_image](https://cloud.githubusercontent.com/assets/1990869/9078855/4e4d74f8-3b61-11e5-8cdf-1f6dcd00148a.png)

**Comment by JoeMurray** [comment]
Let's disable button and display short error message on hover. (There is no UI pattern in CiviCRM for putting a help button there.)

**Comment by JoeMurray** [comment]
Please backport to 4.6 only.

**Comment by pradpnayak** [comment]
Fixed at 
https://github.com/civicrm/civicrm-core/pull/7957
https://github.com/civicrm/civicrm-core/pull/7958
