### ISSUE TITLE
Expose grant application page to anonymous users?

### ISSUE THREAD

**Issue by agileware** [JMAConsulting/biz.jmaconsulting.grantapplications#117]
Does the grant application page extension have the ability to allow anonymous users to access and fill out a grant application page? A quick search did not turn up any instructions and a scan of the available permissions did not turn up anything useful. I'm using CiviCRM 4.6 with Drupal 7.

**Comment by pradpnayak** [comment]
Hi @agileware 

Yes, Anonymous user can access and fill out a grant application page. There is no permission for turning off the access for a particular user role.

Thanks
Pradeep

**Comment by agileware** [comment]
We didn't have CiviContribute enabled before, but enabling it and setting that permission made the grant application page available to anonymous users. Thanks for your help!

**Comment by Edzelopez** [comment]
New permission for submitting grant application added in latest version
