### ISSUE TITLE
Feature Request: Allow grant profile for search results

### ISSUE THREAD

**Issue by shawnholt** [JMAConsulting/biz.jmaconsulting.grantapplications#118]
Advanced search allows you to specify result columns using profiles.  This extension will let you create grant profiles.  it will not let you create search or search result type profiles for grant fields. 

The use case for this is:
1. Grant application requires collecting several things to complete.
2. Created custom multi-select or checkbox fields for collecting info
3. Want to create search results in advanced search which include custom fields.

**Comment by Edzelopez** [comment]
Estimate: 24hrs.

**Comment by JoeMurray** [comment]
Sorry that we did not respond to your feature request inquiry sooner. Best wishes.
