### ISSUE TITLE
500 Error on Grants Dashboard after installing extension

### ISSUE THREAD

**Issue by jmcheung** [JMAConsulting/biz.jmaconsulting.grantapplications#125]
hi guys,

Dev environment: - Wordpress 4.5.3, CiviCRM 4.6.19, grantapplications extension v 1.4.2

Once we install this extension the Grants dashboard breaks. I actually get a 500 error on this page: -
/wp-admin/admin.php?page=CiviCRM&q=civicrm/grant&reset=1

Can you help please.
Jon-man

**Comment by JoeMurray** [comment]
Edsel, can you review for Monday? I'm wondering if there is something here with base_url on jQuery callback or something.

**Comment by jmcheung** [comment]
hi Edsel,

have you been able to look at this?

thank-you,
Jon-man

**Comment by JoeMurray** [comment]
Pradeep, could you look into this? Thx.

**Comment by Edzelopez** [comment]
Hi @jmcheung,

Sorry for the delay, somehow this slipped off my radar. I have fixed the issue and created a new release for 4.6.x. Please download it from here: https://github.com/JMAConsulting/biz.jmaconsulting.grantapplications/releases/tag/v1.4.3

Thanks!

**Comment by Edzelopez** [comment]
@jmcheung closing this issue, please reopen if the error persists...thanks!
