### ISSUE TITLE
Grant Search issue due to extension

### ISSUE THREAD

**Issue by JoeMurray** [JMAConsulting/biz.jmaconsulting.grantapplications#126]
Jon-man noted today that our extension still causes https://issues.civicrm.org/jira/browse/CRM-17022. Please diagnose and address, interacting via chat.c.o if necessary.

**Comment by jmcheung** [comment]
hi Joe, as requested. I'm just posting a comment so I get updated

**Comment by Edzelopez** [comment]
Hi @jmcheung, 

I've fixed this issue and released v1.4.4.(https://github.com/JMAConsulting/biz.jmaconsulting.grantapplications/releases/tag/v1.4.4)

**Comment by jmcheung** [comment]
hi @Edzelopez 

Many thanks - that has fixed it.

Jon-man
