### ISSUE TITLE
Custom field data won't save on Profile in Grant Application Page

### ISSUE THREAD

**Issue by balleyne** [JMAConsulting/biz.jmaconsulting.grantapplications#127]
I've created a Set of Custom Fields for Grants. I can save entries to custom fields successfully when creating a new Grant through the WordPress/CiviCRM backend. But not through my Grant Application Page.

I've created a Grant Application page, using three Profiles. One for the "submit on behalf of an organization", one with additional fields on the applicant (individual contact), and one profile with the Grant custom fields.

When viewing the review or confirmation pages on the grant application, I can see the data I've entered into all the fields, including the grant custom fields:
**Confirmation Page:**
![screenshot from 2016-10-04 08 07 32](https://cloud.githubusercontent.com/assets/71122/19074086/6e86e128-8a0c-11e6-9b3a-db5f1d019016.png)

However, data on the custom fields on the grants isn't saved in the system. Data on the other profiles is saved, and data in the Grant Profile I've created mapping to core CiviGrant fields is saved (e.g. amount requested), but the data from that same Grant profile pertaining to custom fields on the grants isn't saved.

In the email receipt, the data is all displayed as "Array":
**Email Receipt:**
![screenshot from 2016-10-04 08 05 32](https://cloud.githubusercontent.com/assets/71122/19074085/6e83adb4-8a0c-11e6-8019-0edc97cba895.png)

(Note: that the value for amount_requested *is* saved properly in the system, even though it says "Array" in the email receipt.)

And in the system, it's blank:
**Backend View of Custom Fields on Grant submitted through Grant Application Page:**
![screenshot from 2016-10-04 08 07 35](https://cloud.githubusercontent.com/assets/71122/19074087/6e8cd664-8a0c-11e6-806c-62f258950d05.png)

I can't tell if I've done something wrong or if there's a bug. The custom fields work fine when editing a grant in the backend, and the Grant Profile works fine on the Grant Application Page for non-custom fields on the Grant...

**Comment by balleyne** [comment]
I don't quite know what I'm doing enough to create a proper pull request, but I fixed it on my installation with the following patch to CRM/Grant/Form?Grant/Confirm.php:
`703d702
<         CRM_Core_DAO::$_nullArray,`

This was on CiviCRM 4.7.10. Seems to be working fine now, but I don't know if that breaks anything for older installations or something.

**Comment by Edzelopez** [comment]
Hi @balleyne 

I managed to replicate the issue too. I have submitted a fix, but will be available on next release. It seems like you have already managed to fix the issue, but just incase, here's the commit: 8ddd1ebf44bac12cbcac582af7590b55f6586dda
