### ISSUE TITLE
Rich Text Editor field values displayed as escaped HTML source on confirmation page

### ISSUE THREAD

**Issue by balleyne** [JMAConsulting/biz.jmaconsulting.grantapplications#128]
When I add a custom field with Rich Text Editor input to a profile used on the grant application page, on the preview/confirmation page (i.e. before submitting), the text gets displayed as escaped HTML (e.g. "`<p>the text</p>`"), per the following screenshot:
![screenshot from 2016-10-10 10 16 25](https://cloud.githubusercontent.com/assets/71122/19239166/ce97a6ae-8ed2-11e6-8572-8866e7982fc0.png)

I would expect the HTML to be filtered for security, but for allowed HTML tags from the editor to be used instead of escaped.

**Comment by Edzelopez** [comment]
Hi @balleyne,

Thanks for pointing out this improvement. I have fixed it and it will be available in the next release.
Here is the patch if you want to apply it to your instance: https://github.com/JMAConsulting/biz.jmaconsulting.grantapplications/commit/062960477db4395bfabdbac0b87c18c3428d01fa
