### ISSUE TITLE
How to edit a draft version?

### ISSUE THREAD

**Issue by robbrandt** [JMAConsulting/biz.jmaconsulting.grantapplications#129]
If I've submitted a draft application, how do I go back and finish it and submit it?  I see no controls for doing so.  Or am I misunderstanding the purpose of having a draft copy?  I presumed it was to allow an applicant to complete part of the application now, and complete it later.

**Comment by Edzelopez** [comment]
Hey @robbrandt 

You can find your draft copy on the User's contact dashboard. the URL looks something like this: civicrm/user?reset=1

NB. You will need to update your display preferences first, to include grants under Administer > Customize Data and Screens > Display Preferences > Contact Dashboard section.

(There might still be an issue where the grants do not appear on the dashboard, in case that happens, try rebuilding the civicrm menu - i.e hitting http://yoursite/civicrm/menu/rebuild?reset=1 and clearing your caches/templates_c.)
