### ISSUE TITLE
Hide Grant amount

### ISSUE THREAD

**Issue by robbrandt** [JMAConsulting/biz.jmaconsulting.grantapplications#130]
Feature Request
Some of our grants are of an open dollar amount to be decided by the judging committee.

Could there be a checkbox to hide the dollar amount on the application?  Or simply hide it if the amount is 0.00?

**Comment by Edzelopez** [comment]
Hey @robbrandt 

Sounds like a good idea to hide the amount if not specified. I have implemented a quick fix, although I will be refactoring this for a future release. You can apply a patch for now using the commits 836680283208a7dcab9a8c96d80aa5de05b8defc and 53f0e5dec804fd8f6d381fd7918dc6d289984cc1

HTH, 
Edsel

**Comment by robbrandt** [comment]
Thanks.  This needs to be hidden in the email receipt as well.  Thanks.  Everything else looks good.

**Comment by Edzelopez** [comment]
Thanks for the heads up, will include that in our next release.
