### ISSUE TITLE
Using Grant profiles to search

### ISSUE THREAD

**Issue by robbrandt** [JMAConsulting/biz.jmaconsulting.grantapplications#131]
We are using this extension to collect grant applications.  Very helpful.

We would like to build a UI that allows evaluators to search/view applications using profiles.  The grant applications use custom fields created for Grants.  However when I attempt to bring up a profile to search - as I would other profiles - I get this error:

Profile search, view and edit are not supported for Profiles which include fields for more than one record type.

All of the fields in the profile are Grant fields.  No others.

This is in "profile listings mode".  the URL is /civicrm/profile?gid=59&reset=1

Is this a configuration issue, bug, or something that's not supported?

**Comment by Edzelopez** [comment]
Hi @robbrandt 

Unfortunately, this is something not supported by CiviCRM itself. There is no way for one to use a profile configured for gathering info for components to be used as a search application. Only profiles which have fields solely for Contacts and Activities are supported by the listings feature.
