### ISSUE TITLE
grantapplications installation error

### ISSUE THREAD

**Issue by horllste** [JMAConsulting/biz.jmaconsulting.grantapplications#133]
** * This extension enhances profile creation for Grants. * * * Copyright (C) 2012 JMA Consulting * * This program is free software: you can redistribute it and/or modify * it under the terms of the GNU Affero General Public License as * published by the Free Software Foundation, either version 3 of the * License, or (at your option) any later version. * * This program is distributed in the hope that it will be useful, * but WITHOUT ANY WARRANTY; without even the implied warranty of * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the * GNU Affero General Public License for more details. * * You should have received a copy of the GNU Affero General Public License * along with this program. If not, see <http://...@jmaconsulting.biz * JMA Consulting * 215 Spadina Ave, Ste 400 * Toronto, ON * Canada M5T 2C7 */ -- -- Table structure for table `civicrm_grant_app_page` CREATE TABLE IF NOT EXISTS `civicrm_grant_app_p in /home/finagbsr/fedgrantagency.accountant/wp-content/plugins/civicrm/civicrm/CRM/Utils/File.php on line 320

 Sorry, due to an error, we are unable to fulfill your request at the moment. You may want to contact your administrator or service provider with more details about what action you were performing when this occurred.
Could not find the SQL file.

am running 
CiviCRM version 4.7.24
PHP version 5.6.31
and the latest version of wordpress

please how do i fix this

**Comment by andrimont** [comment]
Hello there is the same installation error on Drupal.

>  Sorry, due to an error, we are unable to fulfill your request at the moment. You may want to contact your administrator or service provider with more details about what action you were performing when this occurred.
Could not find the SQL file.

The backtrace gives us this 
`#0 /var/data/sites/photo/public_html/sites/all/modules/civicrm/CRM/Admin/Form/Extensions.php(190): civicrm_api3("Extension", "install", (Array:1))
#1 /var/data/sites/photo/public_html/sites/all/modules/civicrm/CRM/Core/Form.php(447): CRM_Admin_Form_Extensions->postProcess()
#2 /var/data/sites/photo/public_html/sites/all/modules/civicrm/CRM/Core/StateMachine.php(160): CRM_Core_Form->mainProcess()
#3 /var/data/sites/photo/public_html/sites/all/modules/civicrm/CRM/Core/QuickForm/Action/Next.php(61): CRM_Core_StateMachine->perform(Object(CRM_Admin_Form_Extensions), "next", "Next")
#4 /var/data/sites/photo/public_html/sites/all/modules/civicrm/packages/HTML/QuickForm/Controller.php(203): CRM_Core_QuickForm_Action_Next->perform(Object(CRM_Admin_Form_Extensions), "next")
#5 /var/data/sites/photo/public_html/sites/all/modules/civicrm/packages/HTML/QuickForm/Page.php(103): HTML_QuickForm_Controller->handle(Object(CRM_Admin_Form_Extensions), "next")
#6 /var/data/sites/photo/public_html/sites/all/modules/civicrm/CRM/Core/Controller.php(351): HTML_QuickForm_Page->handle("next")
#7 /var/data/sites/photo/public_html/sites/all/modules/civicrm/CRM/Core/Page/Basic.php(398): CRM_Core_Controller->run()
#8 /var/data/sites/photo/public_html/sites/all/modules/civicrm/CRM/Core/Page/Basic.php(156): CRM_Core_Page_Basic->edit(1, NULL)
#9 /var/data/sites/photo/public_html/sites/all/modules/civicrm/CRM/Admin/Page/Extensions.php(121): CRM_Core_Page_Basic->run()
#10 /var/data/sites/photo/public_html/sites/all/modules/civicrm/CRM/Core/Invoke.php(309): CRM_Admin_Page_Extensions->run((Array:3), NULL)
#11 /var/data/sites/photo/public_html/sites/all/modules/civicrm/CRM/Core/Invoke.php(84): CRM_Core_Invoke::runItem((Array:16))
#12 /var/data/sites/photo/public_html/sites/all/modules/civicrm/CRM/Core/Invoke.php(52): CRM_Core_Invoke::_invoke((Array:3))
#13 /var/data/sites/photo/public_html/sites/all/modules/civicrm/drupal/civicrm.module(448): CRM_Core_Invoke::invoke((Array:3))
#14 [internal function](): civicrm_invoke("admin", "extensions")
#15 /var/data/sites/photo/public_html/includes/menu.inc(527): call_user_func_array("civicrm_invoke", (Array:2))
#16 /var/data/sites/photo/public_html/index.php(21): menu_execute_active_handler()
#17 {main}`

The CiviCRM version 4.7.28 is up-to-date.
PHP version 5.6.30-0+deb8u1

**Comment by Edzelopez** [comment]
Thanks for this report @andrimont and @horllste , I will look into it.

**Comment by Edzelopez** [comment]
Hi @andrimont and @horllste 

I have added a [pre-release](https://github.com/JMAConsulting/biz.jmaconsulting.grantapplications/releases/tag/v1.5.2) for the new version which fixes this. We would appreciate it if you could let us know how it works for you and report any bugs if found.

**Comment by andrimont** [comment]
Hello Edzelopez,
Thank you ! The instalation of the pre-release seems fine. One detail : as it seen as a 1.5 version, the refresh in Civi gives an advise to upgrade to the latest version 
: 

> Version 1.5.1 is available. Upgrade

![screenshot 2017-12-29 17 57 03](https://user-images.githubusercontent.com/19648093/34442357-d86f4a44-ecc1-11e7-9107-e1c1372be44b.png)

Regards.

Andrimont

**Comment by Edzelopez** [comment]
Thanks for the feedback @andrimont!
We are working on fixing a few minor bugs, and will release a stable version soon, which will remove the upgrade message you are currently shown on the extensions page.
