### ISSUE TITLE
refactor to remove core overrides

### ISSUE THREAD

**Issue by JoeMurray** [JMAConsulting/biz.jmaconsulting.grantapplications#134]
Please look at effort to refactor to remove core overrides.

**Comment by JoeMurray** [comment]
@Edzelopez please review status on this in next several days.

**Comment by MegaphoneJon** [comment]
@JoeMurray @Edzelopez Check in with @josephlacey?  My understanding is that he's rewritten this extension for recent versions of Civi.

**Comment by JoeMurray** [comment]
Asked him about this at https://chat.civicrm.org/civicrm/pl/ij7w8crr4jygmnt6y5wsyh9sfa

**Comment by Edzelopez** [comment]
We've removed quite a bit of the core overrides. The remaining part is much more complicated and will require hooks to be added in core.
