### ISSUE TITLE
Email address not stored

### ISSUE THREAD

**Issue by tanyabouman** [JMAConsulting/biz.jmaconsulting.grantapplications#138]
I have a grant application page which takes the email address of the applicant.  On the confirmation page, the email shows up properly.  However, in the CRM, it gets stored as "1", rather than the actual email address.  The confirmation email also attempts to send to 1@[mydomain.com].

The grant application sends two individual contact email addresses in $params, email-Primary and email-1, to createProfileContact from CiviCRM Core.  https://github.com/civicrm/civicrm-core/blob/master/CRM/Contact/BAO/Contact.php.  email-Primary contains the correct email address and email-1 comes from a hidden field whose default value is 1.  Inside the profile contact creation, there is a re-formatting of the array that puts email-Primary and email-1 in the same place (formatProfileContactParams).  Since email-Primary gets put in first, email-1 overrides it.

I made a quick fix by inserting the line `$params['email-1'] = CRM_Utils_Array::value('email-Primary', $params);` just before the call to createProfileContact.

I assume that there is a better way to fix the problem, perhaps by removing email-1?   Why is email-1 there in the first place?  Or maybe formatProfileContactParams isn't doing the correct thing?

WordPress: 4.9.8
CiviCRM: 5.2.2
Grant Applications: 1.6.1

**Comment by Edzelopez** [comment]
Thanks for the report @tanyabouman! 
We will take a look at it and provide a fix.

**Comment by Edzelopez** [comment]
Hi @tanyabouman 

I've got a fix ready for this and will release a new version shortly.

**Comment by gnunicorn** [comment]
@Edzelopez Is this release still upcoming? Used your brilliant work, just do discover that now I can't contact the applicants because it didn't save their E-Mail-Address. Bummer.

Otherwise, could you put the patch somewhere? Or do I have to patch the core for this to work?

Thanks heaps!
Your work and contributions are highly appreciated!

**Comment by gnunicorn** [comment]
For the record, the following patch fixes it for me (also contains some logging info):

```diff
iff --git a/CRM/Grant/Form/Grant/Confirm.php b/CRM/Grant/Form/Grant/Confirm.php
index c4d4305..d3ba9e6 100755
--- a/CRM/Grant/Form/Grant/Confirm.php
+++ b/CRM/Grant/Form/Grant/Confirm.php
@@ -360,11 +360,13 @@ class CRM_Grant_Form_Grant_Confirm extends CRM_Grant_Form_GrantBase {
     $params = $this->_params;
     $fields = array();
 
+    Civi::log()->info("params: {paramas}", array('parmas' => $params));
+
     if (!empty($params['image_URL'])) {
       CRM_Contact_BAO_Contact::processImageParams($params);
     }
 
-    $fields = array('email-Primary' => 1);
+    //$fields = array('email-Primary' => 1);
 
     // get the add to groups
     $addToGroups = array();
@@ -459,6 +461,7 @@ class CRM_Grant_Form_Grant_Confirm extends CRM_Grant_Form_GrantBase {
         unset($addToGroups[$k]);
       }
     }
+    unset($params['email-1']);
 
     if (empty($contactID)) {
       $dupeParams = $params;
@@ -482,6 +485,7 @@ class CRM_Grant_Form_Grant_Confirm extends CRM_Grant_Form_GrantBase {
         }
       }
 
+      Civi::log()->info("C1 params: {params}; fields: {fields}", array('params' => $params, 'fields' => $fields));
       $contactID = CRM_Contact_BAO_Contact::createProfileContact(
         $params,
         $fields,
```

**Comment by JoeMurray** [comment]
@Edzelopez please commit fix and close in next few days. Thx.

**Comment by Edzelopez** [comment]
This should be fixed now. Please reopen if necessary.

**Comment by sunnycs121** [comment]
This is occurring in version 1.6.2

**Comment by JoeMurray** [comment]
Can you provide your CiviCRM version and CMS and CMS version?
