### ISSUE TITLE
Error on Contact Dashboard when Grant Applications enabled

### ISSUE THREAD

**Issue by robbrandt** [JMAConsulting/biz.jmaconsulting.grantapplications#139]
I am newly updated to CiviCRM 5.4.1, and the most recent Grant Applications release.

When I try and access the Contact Dashboard at https://domain.org/civicrm/user?reset=1
I get this error:

Fatal error: Call to a member function getTemplateFileName() on null in /home/crm/public_html/sites/all/ext/biz.jmaconsulting.grantapplications/grantapplications.php on line 365

I think this existed prior to my upgrade as well, we just didn't expose the dashboard to contacts.  I seem to remember seeing it when we were considering the dashboard previously.

**Comment by robbrandt** [comment]
Is it possible for you to show the fix so I can patch up my installation?  We want to make the dashboard live but we can't disable this extension.

**Comment by Edzelopez** [comment]
Hi @robbrandt 

Sorry for the delay on this. Some more compatibility issues were noted with the 5.x version, which delayed the release of the new version. Here is a patch you can apply: https://gist.github.com/Edzelopez/d13e88fcbc20e41030d7d9ab3a40bc90

**Comment by JoeMurray** [comment]
@Edzelopez please fix or close in next little while. Thx.

**Comment by robbrandt** [comment]
Hi.  I have been remiss in following up on this issue.

The patch above doesn't really solve the issue.  I applied it and it worked, but then it failed again.  Something isn't consistent.  So we still can't use the Contact Dashboard.  Exactly the same error as above when it fails.

**Comment by robbrandt** [comment]
Correction, the patch does work.  My test environment had the extension directory configured as pointing to the live extension directory.  So changes to extensions in the test environment weren't actually seen by CiviCRM.

**Comment by robbrandt** [comment]
Issue is not really closed though because Grant Applications still won't show in the Dashboard, this just avoids the query.

**Comment by agileware-justin** [comment]
I actually think this issue is a blocker to allowing people to use an on-line grant submission process. There is no way to allow a user to view their own grants or resume a draft grant - as this function would be provided by the Contact Dashboard.

**Comment by Edzelopez** [comment]
This should now be addressed in our latest 1.7.1 release

**Comment by Edzelopez** [comment]
This should now be fixed
