### ISSUE TITLE
page not found

### ISSUE THREAD

**Issue by JoeMurray** [JMAConsulting/biz.jmaconsulting.grantapplications#142]
After installing, Grants > New Grant Application Page gives unfriendly Page Not Found error http://jma.staging.autismontario.com/civicrm/admin/grant/apply?reset=1&action=add possibly due to D8??

**Comment by Edzelopez** [comment]
For D8, you will need to flush caches after installation of any CiviCRM extension, in order for the menu paths to resolve to their callback functions.
