### ISSUE TITLE
Update breadcrumb

### ISSUE THREAD

**Issue by JoeMurray** [JMAConsulting/biz.jmaconsulting.grantapplications#144]
On New Grant on dmaster, the breadcrumb shows CiviGrant Dashboard. That's good. On jma.staging.autismontario.com New Grant, the breadcrumb is not updated properly. Not sure if this due to Grant Applications all the time, or D8.

![2018-09-24_13-19-17](https://user-images.githubusercontent.com/300943/45967720-e043be80-bffc-11e8-8c0a-4e87e3fee7f5.png)

**Comment by Edzelopez** [comment]
This looks like a D8/DE customization. I think we have fixed it.

Here is how it appears now.

<img width="737" alt="Screenshot 2020-07-26 at 1 07 43 PM" src="https://user-images.githubusercontent.com/1990869/88474084-090ea500-cf41-11ea-8725-176089084ba8.png">
