### ISSUE TITLE
missing email value in Thank You

### ISSUE THREAD

**Issue by robbrandt** [JMAConsulting/biz.jmaconsulting.grantapplications#145]
On our Grant Application Thank You pages, we are getting this message:

Your grant application has been sent for processing. Please print this page for your records.
An email receipt has also been sent to .

There is no email address included at the end.  The template shows that the value would be $email.

Both the logged in user and the person designated as a cc in the configuration are getting the receipts, so the issue seems to be limited to displaying the value in the template.

**Comment by JoeMurray** [comment]
Sorry about this problem, @robbrandt . Could you provide the version of the extension you're using, and the CMS and its version? Thanks!

**Comment by JoeMurray** [comment]
@Edzelopez please look into this in next few days.

**Comment by Edzelopez** [comment]
This should be addressed in our latest release: https://github.com/JMAConsulting/biz.jmaconsulting.grantapplications/releases/tag/1.7
