### ISSUE TITLE
Better subject for receipt email?

### ISSUE THREAD

**Issue by robbrandt** [JMAConsulting/biz.jmaconsulting.grantapplications#146]
Enhancement request here.

We have a variety of "grants" we administer.  All of the send a receipt (cc'ed to the manager) with the subject "Grants - Receipt".  I don't see anywhere to change this.

Can this be altered so that it includes the title of of the grant?  For example "Graduate Student Award - Applicaiton Receipt".

**Comment by Edzelopez** [comment]
Hi @robbrandt ,

You can alter the message subject for the receipt by navigating to Administer > CiviMail > Message Templates and clicking on the Grants Receipt message template under the System Workflow Messages tab. However, the grant title does not seem to be an available token. It's a good feature request though, to allow grant tokens to be specified in the receipt. @JoeMurray should we work on supporting this in the next release?

**Comment by JoeMurray** [comment]
We could add this for USD$125. Please reopen if you can fund this.
