### ISSUE TITLE
Shortcodes w Civi 5.0

### ISSUE THREAD

**Issue by ddoligalski** [JMAConsulting/biz.jmaconsulting.grantapplications#147]
I am not having success getting the shortcode recognized with Civi 5.13.6.  It looks like some of the shortcode processing may have changed.   Any thoughts would be appreciated.  -Dave

**Comment by MegaphoneJon** [comment]
@ddoligalski I believe that @josephlacey has rewritten this extension for the latest versions of CiviCRM.  He's "jlacey" on Mattermost.

**Comment by JoeMurray** [comment]
@Edzelopez could you look into this in next day or two?

**Comment by josephlacey** [comment]
As noted in Mattermost, I've upgrade Grant Programs, not Grant Applications.

**Comment by Edzelopez** [comment]
@ddoligalski sorry for the extremely late comment. Do you still have issues with this?

**Comment by Edzelopez** [comment]
Closing this, please reopen if necessary.
