### ISSUE TITLE
Error when leaving Save as Draft Enabled? blank

### ISSUE THREAD

**Issue by spexb** [JMAConsulting/biz.jmaconsulting.grantapplications#148]
When I leave the checkbox for _Safe as Draft Enabled?_, I get an error message:
![grant application](https://user-images.githubusercontent.com/33966222/70867774-8441be80-1f4f-11ea-9ca6-3491adb5bc3c.png)

CiviCRM 5.20.0
Grant Application Pages 1.6.1

**Comment by JoeMurray** [comment]
Edsel, could you diagnose and address this issue with saving a draft application. @spexb could you indicate what version of CiviCRM and Wordpress/Drupal/Joomla you are using?

**Comment by spexb** [comment]
I'm using WordPress 5.3.1.

**Comment by Edzelopez** [comment]
Hi @spexb 

I've fixed this in my latest commit. Please let me know if you have any questions about applying the patch [here](https://github.com/JMAConsulting/biz.jmaconsulting.grantapplications/commit/ff0b97f9ad2e0ce1bfe2992ab2b50e32e2160f8a). Thanks!

**Comment by JoeMurray** [comment]
If @spexb confirms this fix we should tag a new release.

**Comment by spexb** [comment]
Yippeee! It works. Gracias beaucoup!

**Comment by spexb** [comment]
Just the Grants|Dashboard shows:
_"There has been a critical error on your website. Please check your site admin email inbox for instructions."_

**Comment by Edzelopez** [comment]
Can you try applying the patch here https://github.com/JMAConsulting/biz.jmaconsulting.grantapplications/commit/fbae743522e34061fbfcb9c500f8cf1a588d57a3 ?

**Comment by Edzelopez** [comment]
Closing this since issue has been addressed.
