### ISSUE TITLE
Registering a CiviEvent with this enabled on 5.20 gives WP 500 error

### ISSUE THREAD

**Issue by shohidgmcvo** [JMAConsulting/biz.jmaconsulting.grantapplications#149]
Hi,

The site is on Wordpress 5.3. PHP 7. CiviCRM 5.20. the extension version it's on is 1.6.1.
When attempting to sign up for an Event (event type: Training) and this extension is enabled in the background, the confirmation page of the event gives a 500 error "There has been a critical error on your website".

This all used to work before upgrading from 5.13.4. Please can you look into this.

Thanks.

Shohid

**Comment by JoeMurray** [comment]
Could you provide relevant messages from the CiviCRM, PHP or Apache logs that led you to suspect it was this extension? Just FYI https://www.westhost.com/knowledgebase/display/WES/What+Is+A+500+error

Or does it work when the extension is disabled, then enabling the extension causes this error? That's unexpected, because this extension would not normally be loaded when serving an event registration page.

**Comment by shohidgmcvo** [comment]
Hi @JoeMurray 

Thank you for responding. The confirmation page only shows when this extension is disabled. When I enable this extension, it shows the 500 error on the confirmation page.

This is the debug.log file:

[19-Dec-2019 10:42:34 Europe/London] PHP Notice:  Undefined offset: 0 in /public_html/wp-content/plugins/files/civicrm/extensions/biz.jmaconsulting.grantapplications/CRM/Core/BAO/UFGroup.php on line 2350
[19-Dec-2019 10:42:34 Europe/London] PHP Notice:  Undefined offset: 1 in /public_html/wp-content/plugins/files/civicrm/extensions/biz.jmaconsulting.grantapplications/CRM/Core/BAO/UFGroup.php on line 2350
[19-Dec-2019 10:42:35 Europe/London] PHP Fatal error:  Uncaught Error: Call to undefined method CRM_Core_BAO_UFGroup::getFrontEndTitle() in /public_html/wp-content/plugins/civicrm/civicrm/CRM/Event/BAO/Event.php:1493

Please let me know if you can resolve this.

Kind regards,

Shohid

**Comment by Edzelopez** [comment]
Hi @shohidgmcvo 

This extension hasn't yet been made compatible with the 5.20 version of CiviCRM, given that it is so recent. I will however work on a patch that you can use with your version.

**Comment by shohidgmcvo** [comment]
Thank you @Edzelopez

If you can write the patch for 5.19.4, that would be great.

Kind regards,

Shohid

**Comment by shohidgmcvo** [comment]
Hi @Edzelopez 

Is there an update on this patch for 5.19.4? Thanks.

Shohid

**Comment by Edzelopez** [comment]
Hi @shohidgmcvo,

The patch is available here: https://github.com/JMAConsulting/biz.jmaconsulting.grantapplications/commit/fbae743522e34061fbfcb9c500f8cf1a588d57a3

**Comment by shohidgmcvo** [comment]
Hi @Edzelopez 

Thank you! I will apply the patch and let you know the outcome. Thanks again.

Shohid

**Comment by seamuslee001** [comment]
We had a report in from gmcvo the the patch has worked closing this issue
