### ISSUE TITLE
Grant Applications replaces all the default CiviCRM shortcodes instead of just adding the specific Grant Application shortcodes

### ISSUE THREAD

**Issue by agileware-justin** [JMAConsulting/biz.jmaconsulting.grantapplications#151]
Grant Applications replaces all the default CiviCRM shortcodes instead of just adding the specific Grant Application shortcodes. See file https://github.com/JMAConsulting/biz.jmaconsulting.grantapplications/blob/master/shortcode-wp/includes/civicrm.shortcodes.php

I think this PR on the Veda's GDPR extension demonstrates a different method to add a new WordPress shortcode, see https://github.com/veda-consulting/uk.co.vedaconsulting.gdpr/pull/217

**Comment by agileware-justin** [comment]
Actually, I'll close this as it would be addressed by #134

**Comment by Edzelopez** [comment]
Thanks for the info Justin!

**Comment by JoeMurray** [comment]
Thanks for this report about an issue due to change in WP editor. We will be addressing this in April.

**Comment by JoeMurray** [comment]
Reopening as we're not confident that solving #134 will completely resolve this issue.

**Comment by Edzelopez** [comment]
@agileware-justin this should now be addressed in our latest release: https://github.com/JMAConsulting/biz.jmaconsulting.grantapplications/releases/tag/1.7
