### ISSUE TITLE
Upgrade from 1.7.0 to 1.7.1 fails

### ISSUE THREAD

**Issue by MegaphoneJon** [JMAConsulting/biz.jmaconsulting.grantapplications#158]
It's line 29 in `biz.jmaconsulting.grantapplications/grantapplications.php`.  Because of how this SQL is run I can't see the whole SQL statement, but I can see that I'm getting an "already exists" error on one of the `INSERT` statements.

**Comment by Edzelopez** [comment]
Hey @MegaphoneJon 

Yes, we've noticed that and will be pushing a new release out soon. Sorry for the inconvenience!

**Comment by Edzelopez** [comment]
@MegaphoneJon the new release should solve this. Closing now, please reopen if necessary!
