### ISSUE TITLE
Extension breaks formatting / layout of profile editor page

### ISSUE THREAD

**Issue by webmaster-cses-org-uk** [JMAConsulting/biz.jmaconsulting.grantapplications#172]
When extension is enabled, the tabbed layout of the CiviCRM Profiles page is broken.

This is because the extension overrides CRM_UF_Page_Group and CRM_UF_Page_ProfileEditor, but the bundled files are out-of-date.

CRM_UF_Page_Group is missing the following section at line 365 of civicrm-core/CRM/UF/Page/Group.php:
```php
    Civi::resources()
      ->addScriptFile('civicrm', 'templates/CRM/common/TabHeader.js', 1, 'html-header')
      ->addSetting([
        'tabSettings' => ['active' => $_GET['selectedChild'] ?? NULL],
      ]);
```
This file needs to be updated to the latest version, but it would be better if a long-term solution could be found that doesn't involve replacing one of the core files. Possibly one of:
- Make grant_type a pseudoconstant and update core version accordingly (would need agreement from core maintainers).
- Use a template hook to populate just the specific part of the table, leaving the rest of the page as default.

It is no longer necessary to override CRM_UF_Page_ProfileEditor as the core version now includes support for other entities by pattern matching (see line 194 of civicrm-core/CRM/UF/Page/ProfileEditor.php):
```php
        default:
          if (strpos($entityType, 'Model') !== FALSE) {
            $entity = str_replace('Model', '', $entityType);
            $backboneModel = self::convertCiviModelToBackboneModel(
              $entity,
              ts('%1', [1 => $entity]),
              $availableFields
            );
            if (!empty($backboneModel['schema'])) {
              $civiSchema[$entityType] = $backboneModel;
            }
          }
          if (!isset($civiSchema[$entityType])) {
            throw new CRM_Core_Exception("Unrecognized entity type: $entityType");
          }
```
Suggest that this file be removed from the extension.

The purpose of the override of CRM/Core/Page/AJAX/Location.php (adding "File" to the list of options when calculating field defaults) is unclear? This seems to be in-date, however.

**Comment by JoeMurray** [comment]
Thanks for these useful PRs! @monishdeb please review all issues and once resolved/merged tag a new release.

**Comment by Edzelopez** [comment]
Yes, I agree that a long term solution is needed here instead of keeping the bundled files up to date. WIll investigate more on making grant_type a pseudoconstant which seems promising, but may have pushback from the core maintainers.

**Comment by jmcclelland** [comment]
I agree that a long term fix is the best option - this will continue to cause breakage moving forward. But... in the meantime I just pushed the temp fix of adding the missing code. You may want to bump the required CiviCRM version to 5.39 (it works for me on that version, maybe it also works on earlier versions too).

**Comment by monishdeb** [comment]
Closing this ticket as the related PR is merged now.
