### ISSUE TITLE
Email address not populated for logged-in user

### ISSUE THREAD

**Issue by webmaster-cses-org-uk** [JMAConsulting/biz.jmaconsulting.grantapplications#177]
If a user is logged in when accessing the grant application page, the primary email address is not populated automatically.

Will work on a fix.

**Comment by webmaster-cses-org-uk** [comment]
Turns out this is because an email address field is needed in one of the form profiles for this to work correctly.

Have created https://github.com/JMAConsulting/biz.jmaconsulting.grantapplications/pull/178 to clarify documentation and fix associated minor issue in template logic.

**Comment by Edzelopez** [comment]
Closing this since PR has been merged. Thanks so much for the fix!
