### ISSUE TITLE
Extension requires upgrade / refactoring for migration of CiviGrant to extension

### ISSUE THREAD

**Issue by webmaster-cses-org-uk** [JMAConsulting/biz.jmaconsulting.grantapplications#182]
CiviCRM 5.47 migrates CiviGrant from a component to a core extension. This extension needs to be updated to account for this change.

https://civicrm.org/blog/dev-team/civicrm-547-release

Haven't yet had time to extensively check compatibility, but one thing that is broken is the following on line 376 of grantapplications.php:

``$userDashboard = $components['CiviGrant']->getUserDashboardObject();``

The CiviGrant component no longer exists so this results in an error `Call to a member function getUserDashboardObject() on null`.

We do not use the grant user dashboard component in our use case so I have just commented this section out for now, pending a permanent fix.

**Comment by monishdeb** [comment]
@webmaster-cses-org-uk can you try the fix https://github.com/JMAConsulting/biz.jmaconsulting.grantapplications/pull/185 ?

**Comment by webmaster-cses-org-uk** [comment]
> @webmaster-cses-org-uk can you try the fix #185 ?

Thank you for this - I have tried the fix and yes the dashboard now loads correctly without error.

A couple of things, however:

1. The section shows even if it is empty (i.e. there are no grants).
2. There seems to be an unnecessary second section header "Manage Grant Application Pages"?

![image](https://user-images.githubusercontent.com/72983627/177000134-2deee2af-f4d0-4936-b9cd-e13d851c9b67.png)

I don't know how possible this is, but ideally we would be able to enable / disable the grants pane from the Contact Dashboard options in Administer > Customise Data and Screens > Display Preferences

![image](https://user-images.githubusercontent.com/72983627/177000156-571de1a6-96c7-46bc-be2d-bc68533a2a43.png)

**Comment by JoeMurray** [comment]
Hi @webmaster-cses-org-uk , 
1. The pattern of having a section show even if there is no content is present in a number of places in CIviCRM core, so I'm not inclined to change that especially without funding.
2. Manage Grant Application Pages is similar to Manage Contribution Pages (and Manage Events): it shows the pages that have been created and configured to allow users to apply for grants.
3. I like the idea of an option on Contact Dashboard Display Preferences to enable/disable display of the Grants tab. We could implement that for USD$375.

**Comment by webmaster-cses-org-uk** [comment]
@JoeMurray Thanks for your feedback.

1. Yes this is fine (and as you say consistent). I think the issue is just confused by having the second header.
2. Unless I've misunderstood, the purpose of this dashlet (and how it seemed to work before) was to allow a user to view and continue their saved/draft grant applications, not to manage grant application *pages*. Why would a front-end / public user be altering the grant application page setup? Apologies if I've got the wrong end of the stick here.
3. Noted.

**Comment by monishdeb** [comment]
Moved to https://lab.civicrm.org/extensions/grantapplications/-/issues/182
