### ISSUE TITLE
Grant application is making Caldera Froms unusable

### ISSUE THREAD

**Issue by Shwele** [JMAConsulting/biz.jmaconsulting.grantapplications#186]
After installing this module as test, my Caldera Forms weren't responsive at all. We could click to edit any that we wanted but switching between tabs, editing fields, everything wasn't responsive after that part.

Can provide more info if needed, but I think its easy to replicate for anyone and test this.

Here you can see how it looks like when its enabled on Wordpress Civicrm: [https://imgur.com/a/6pkfIyG](https://imgur.com/a/6pkfIyG)

**Comment by JoeMurray** [comment]
@monishdeb once the Assam floods recede and you are back at work, please look at this.

**Comment by monishdeb** [comment]
@Shwele we have fixed some fatal issues with Civi 5.50+  and published a new release 1.8 (please check the latest release at https://civicrm.org/extensions/grant-application-pages). I have tested Caldera Form with this new release and didn't encounter any issue. Can you please upgrade Grant Applications to 1.8 and check if it resolves the CF issue?

**Comment by monishdeb** [comment]
Moved to https://lab.civicrm.org/extensions/grantapplications/-/issues/186
