### ISSUE TITLE
Merge with CiviGrant?

### ISSUE THREAD

**Issue by MegaphoneJon** [JMAConsulting/biz.jmaconsulting.grantapplications#187]
It seems like overrides are an ongoing issue with this extension - but now that CiviGrant isn't in core, I think there's a strong argument for merging grant application functionality into CiviGrant itself.

**Comment by JoeMurray** [comment]
@seamuslee001 could you review with @monishdeb and discuss with me?

**Comment by monishdeb** [comment]
Moved to https://lab.civicrm.org/extensions/grantapplications/-/issues/187
