### ISSUE TITLE
Edit default amount on grant application page

### ISSUE THREAD

**Issue by alecmeltzer** [JMAConsulting/biz.jmaconsulting.grantapplications#22]
The "Requested Amount" form field is not accessible on the grant application pages. Default amount value is printed to the screen, but no input form is available to change the default.

**Comment by JoeMurray** [comment]
Just to explain a bit more: the required total amount field is the amount requested in the default currency, while the optional amount requested field is in the original currency. If you are only working with a single currency, don't bother using the amount requested field.
