### ISSUE TITLE
text fields for Profile selection on grant application page

### ISSUE THREAD

**Issue by pradpnayak** [JMAConsulting/biz.jmaconsulting.grantapplications#94]
From Dana:
In setting up a Grant Application on the profiles I don't get any dropdown or select I have to add by profile IDs. This affects On Behalf of Orgs profile selection too.
![grants-app-no-profile-select](https://cloud.githubusercontent.com/assets/2053075/6146009/12635ba6-b20e-11e4-99cd-64b6e016bca0.png)

**Comment by pradpnayak** [comment]
-- We are unable to replicate the error. But i remember in past for different project we had similar problem in case of selecting Profile for Event. The issue was because of custom theme. Are you able to see dropdown for profile on Event or Contribution page?

**Comment by danaskallman** [comment]
I was testing with default theme, but this is admin area too, so not sure I fillow how the theme would affect it. Yes, it works on Events and Contribution pages too.

I just downloaded the latest version and grants application profile selection is now working too.

**Comment by JoeMurray** [comment]
So let's close for now.

**Comment by danaskallman** [comment]
Yes, we can re-open if issue returns
