### ISSUE TITLE
No grants visible on Contact Dashboard

### ISSUE THREAD

**Issue by pradpnayak** [JMAConsulting/biz.jmaconsulting.grantapplications#95]
From Dana:

If I save the grant it does save, but does not show on the User Dashboard. I did go enable the checkbox for it to appear and cleared the cache and still the grants I saved did not appear in my user/contact dashboard for me to ho back and edit. This was when I saved grant applications as an indvidual. When I added on behalf of org my contact dashboard went blank for the individual contact and did not display grants in the organization contact dashboard.

**Comment by pradpnayak** [comment]
Did you replace ReplaceInfo/Info with CRM/Grant/Info.php? We need to over-ride core file to get the grant visible on User Dashboard.

 Currently, the User Dashboard is only intended to show Grants that are in Draft state. Viewing from User Dashboard was not in scope so far. Is it a desired feature? If so, we need a spec for things like hiding of certain fields during review process?

**Comment by danaskallman** [comment]
Yes, this works if I replace the core file. 

Is there a way to do this without having to replace a core file? Maybe using the custom directory or something, which would make updates of core much easier?

**Comment by pradpnayak** [comment]
Fixed at https://github.com/JMAConsulting/biz.jmaconsulting.grantapplications/pull/122

**Comment by Edzelopez** [comment]
Unfortunately, we tried using a custom version of the file in our extension and using hooks but none of the methods seemed to work, which left us with the final resort of providing a file which could be replaced :(

**Comment by JoeMurray** [comment]
So we are currently doing pro bono implementation of page run hook for 4.7 in order to allow this feature request to be implemented without an override. Dana - any chance for some money for this? We're investing about a day's effort, but will take what you can send our way.

**Comment by Edzelopez** [comment]
Implementation done in latest version.
