### ISSUE TITLE
New Grant Application Page forwards to generic CiviCRM Administration Page

### ISSUE THREAD

**Issue by brentdec** [JMAConsulting/biz.jmaconsulting.grantapplications#96]
I was unable to install the Grants Application extension automatically, so I manually installed it. Everything acts as though it's installed correctly. However, when I try to access the New Grant Application  Page, instead I get the generic CiviCRM Admin page.

![extension page](https://cloud.githubusercontent.com/assets/11293960/6462757/d2ed6342-c160-11e4-9461-f12ca10bc9f8.png)
![new grant page](https://cloud.githubusercontent.com/assets/11293960/6462758/d30cda38-c160-11e4-86f7-d1d8b9414864.png)

Thanks for your prompt reply, as I'm very eager to begin using your extension!

**Comment by Edzelopez** [comment]
Hi @brentdec 

Could you try rebuilding your menu? Please add civicrm/menu/rebuild?reset=1 to your site's base URL and let me know if that worked for you.

Thanks!

**Comment by pradpnayak** [comment]
Hi @brentdec 

Could you tell us what version of CiviCRM are you using? Did you add Extension url correctly in Resource url?

Thanks
Pradeep

**Comment by brentdec** [comment]
Wow!

Now that’s prompt!

I’m sorry, but how do I rebuild the menu? 

Brent

**Comment by Edzelopez** [comment]
Just try adding civicrm/menu/rebuild?reset=1 to your site's domain.

For example,

http://mysite.com/civicrm/menu/rebuild?reset=1 for a Drupal site

http://mysite.com/wp-admin/admin.php?page=CiviCRM&q=civicrm/menu/rebuild&reset=1 for a WP site

**Comment by pradpnayak** [comment]
2 ways:

1. Cleanup Caches and Update path
Administer-> System Settings -> Cleanup Caches and Update Paths : Cleanup Caches

2. Hitting url http://[domain_name]/civicrm/menu/rebuild?reset=1

**Comment by brentdec** [comment]
Pradeep,

I am using version 4.5.6

I’m unclear on the Extension URL…

**Comment by brentdec** [comment]
Rebuilt menus - no joy

Performed Clean Up Cache and update path - no joy

**Comment by brentdec** [comment]
See photo - Grant Dashboard

**Comment by Edzelopez** [comment]
Hi @brentdec 

Unfortunately, we haven't released a 4.5.x compatible extension yet, but will do so in the near future. It is currently being tested, so any help with testing with the 4.5.x version is much appreciated! 

Just a tip, you can add an extension resource URL at Administer >> System Settings >> Resource URLs

This would allow you to download the extension from CiviCRM itself.

**Comment by brentdec** [comment]
No problem helping…

BTW

Currently the extension resource URL is:

http://www.truevoicefoundation.org//home/decdigital/www/www/sites/default/files/civicrm/extensions/ <http://www.truevoicefoundation.org//home/decdigital/www/www/sites/default/files/civicrm/extensions/>

that appears weird to me (the two slashes after domain). Is it correct (as far as you can tell?)

**Comment by Edzelopez** [comment]
Since the site directory is /home/decdigital/www/www, the extension resource URL should be

http://www.truevoicefoundation.org/sites/default/files/civicrm/extensions/

**Comment by brentdec** [comment]
great - I’ll try reinstalling the extension and let you know how it works

**Comment by Edzelopez** [comment]
@brentdec 
Sure.

btw, I just changed the links from your previous post to remove the actual site name for security reasons. 

Cheers,
Edsel

**Comment by brentdec** [comment]
Just downloaded a new copy from Github, installed manually, rebuilt menus - working!

**Comment by pradpnayak** [comment]
closing this as its fixed
