### ISSUE TITLE
WP Shortcode for 4.5

### ISSUE THREAD

**Issue by danaskallman** [JMAConsulting/biz.jmaconsulting.grantapplications#98]
I was looking at what's in the shortcode-wp directory and noticing that the core file is using 4.4 not 4.5 civicrm.js file. 

If I am understanding correctly, we are needing to replace for files for this to work in WP, is that correct? If so, what can be done to change it so core files are not needed to be replaced?

**Comment by JoeMurray** [comment]
Please rewrite to make use of https://issues.civicrm.org/jira/browse/CRM-16650

**Comment by pradpnayak** [comment]
Fixed at https://github.com/JMAConsulting/biz.jmaconsulting.grantapplications/pull/122
